### ISSUE TITLE
Purpose of small bed plate holes

### ISSUE THREAD

**Issue by kozross** [rogerlz/Doron-Velta#15]
The aluminium bed plate has three small (~2.4mm diameter) holes in it, as highlighted below:

![image](https://github.com/user-attachments/assets/be6b0a20-709c-47b8-adfb-9600795e04f2)

What is the purpose of these holes? According to the CAD model, they don't attach to anything, and they're only big enough for M2 hardware.

**Comment by rogerlz** [comment]
they are m3 tapped holes, and you can use them for ground, thermal fuse and an extra thermistor
