### ISSUE TITLE
BOM update

### ISSUE THREAD

**Issue by Life0fBrian** [rogerlz/Doron-Velta#2]
Can you please add the used power inlet to the bom.
Should be `IEC320 C14 inlet` if I'm right.

**Comment by kyleisah** [comment]
#3 fixes this issue

**Comment by kyleisah** [comment]
Removing the BOM from the readme might be a good idea, and just having a CSV or a separate .md for this would probably be best. I can help you export one from CAD, Roger. 😄

**Comment by Life0fBrian** [comment]
I would prefer a .md to be able reading it everywhere. 
Thanks for your help. 
There should be an update on the 5 mm dowell pins as well to 25 mm length.

**Comment by rogerlz** [comment]
thank you both. BOM is now on a separate file, and I fixed the dowel pin length.
