### ISSUE TITLE
Magnetic ball arms?

### ISSUE THREAD

**Issue by visualinventor** [rogerlz/Doron-Velta#7]
This is a well done Voron like design so kudos to you, for not being great at CAD I'd say you're doing really well. 
This isn't an issue per se but a curiosity. I'm curious as to why you didn't go with magnetic ball arms instead?

**Comment by rogerlz** [comment]
Hey!

Thanks for the feedback.

I think the README explains the reasons. I already had the FLSUN Q5 arms, the design was meant as a meme, and this is my first delta, so I honestly don't know the (dis)advantages over magnetic ball arms.

It is definitely something I'd like to play with at some point and I would happily give feedback on a mod to use them.

Ty
Roger
