### ISSUE TITLE
Bolts for feet too short

### ISSUE THREAD

**Issue by ViperWorx** [rogerlz/Doron-Velta#8]
Hi Seti here,

I'm just checking fixings and with the feet in the CAD the M5x60 is too short, this needs to be at least an M5x70 to engage properly with the extrusion. I have printed mine, but ripped the model straight from the CAD, so I would assume that the standard Voron v2/Trident feet will have the same issue.

**Comment by rogerlz** [comment]
Hey!

Thanks for the feedback. You are the first one I hear about needing a m5x70. Anyway, those screws don't play any vital role in the structure. They are only meant to keep the feet in place and help assemble the 2020s straight.

The new R2 version now uses m5x16. 

Ty
Roger
