### ISSUE TITLE
Sensorless?

### ISSUE THREAD

**Issue by hreality** [rogerlz/Doron-Velta#9]
Do you know of or have any information to make this sensorless for A, B, C?

**Comment by yzeroy** [comment]
As official BTT user guide states, just use jumper caps as in screenshot, unplug endstop wires from board and change klipper config as any for other kinematics. BUT, keep in mind that sensorless homing is not as precise as fysical endstops, repeatability is not as precise.

![obrazek](https://github.com/user-attachments/assets/d2e0f7c8-9569-4a54-af83-00f9c7310f9e)

[https://github.com/bigtreetech/SKR-Pico](url)

**Comment by hreality** [comment]
Thank you for the response.  While not 'this' delta I did use you as a template and discovered that variations in endstops can cause exaggerated artifacts in print.  That being said, using a sensorless option where each endstop is a 'percieved' balance is an even worse idea.
